# Generated by Django 3.2.3 on 2021-05-25 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microtask', models.TextField()),
                ('floorNo', models.IntegerField(default=1)),
                ('roomNo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('Name_of_microtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mto')),
            ],
        ),
    ]
