# Generated by Django 3.2.3 on 2021-05-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malrequirements',
            old_name='Name_of_microtask',
            new_name='name_of_microtask',
        ),
        migrations.RemoveField(
            model_name='malrequirements',
            name='date',
        ),
        migrations.RemoveField(
            model_name='malrequirements',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='mto',
            name='floorNo',
        ),
        migrations.RemoveField(
            model_name='mto',
            name='roomNo',
        ),
    ]
