# Generated by Django 3.2.3 on 2021-05-25 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210525_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
