# Generated by Django 3.2.3 on 2021-05-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mto_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malrequirements',
            name='title',
        ),
    ]
