# Generated by Django 3.2.3 on 2021-05-25 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_malrequirements_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='malrequirements',
            name='status',
            field=models.CharField(choices=[('p', 'Posted'), ('n', 'Not posted')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
