# Generated by Django 3.2.3 on 2021-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_malrequirements_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malrequirements',
            name='status',
            field=models.CharField(choices=[('n', 'Not posted'), ('p', 'Posted')], default=1, max_length=1),
        ),
    ]
